### ISSUE TITLE
positional encoding init 문제

### ISSUE THREAD

**Issue by woaksths** [sooftware/PyTorch-Transformer#1]
안녕하세요. positonal encoding에서 여쭤볼게 있어서 글 남깁니다. 

transformer.py 91, 128 라인에서 Positional encoding initialize시에 
dropout을 인자로 넘기는게 맞는 것인지 확인 부탁드립니다. 

(d_model, max_len)를 넘겨야하는게 아닌가 싶은데,  (d_model, dropout)으로 되어있길래
혹시 제가 잘못이해하고 있는 것인지 답변주시면 감사드리겠습니다.

**Comment by woaksths** [comment]
앗 참고로 리드미에 있는 사용법 참고하고, 코드 돌려보았는데 positional encoding 이외에도 
에러가 너무 많길래 제대로 돌아가는 코드인지 여쭤보고 싶습니다.

**Comment by sooftware** [comment]
음... dropout 인자 설정이 잘못되어 있는 것 같네요! ㅠ.ㅠ   
전에 돌아가는 것을 확인했었으나, 전에 수정하면서 조금 꼬인 것 같습니다.  
  
지금 일이 바빠 이 레포는 관리를 못하고 있네요. 말씀해주셔서 감사합니다.

**Comment by woaksths** [comment]
답변 감사합니다.
